repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
        files: myapp/.*\.go$
      - id: go-imports
        files: myapp/.*\.go$
      - id: no-go-testing
        files: myapp/.*\.go$
      - id: golangci-lint
        files: myapp/.*\.go$
      - id: go-unit-tests
        files: myapp/.*\.go$
      # - id: validate-toml
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
