version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --requirepass redisPassword
    ports:
      - "6379:6379"
  
  chatroom_list:
    image: redis:latest
    command: redis-server --requirepass redisPassword
    ports:
      - "6380:6380"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  main_server:
    image: main_server:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - redis
      - mongodb
    environment:
      - REDIS_ADDR=redis:6379
      - DB_URL=postgres://postgres:rootpassword@postgresql:5432/postgres?sslmode=disable
      - MONGO_URL=mongodb://mongodb:27017

volumes:
  postgresql_data:
  mongodb_data:
