# docker-compose.yml
version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  db_init:
    build: ./db_init
    image: db_init_image
    environment:
      - POSTGRES_PASSWORD=rootpassword
    depends_on:
      - postgresql

  redis:
    image: redis:latest
    command: redis-server --requirepass redisPassword
    ports:
      - "6379:6379"

  chatroom_list:
    image: redis:latest
    command: redis-server --requirepass redisPassword
    ports:
      - "6380:6380"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  main_server:
    build: ./myapp
    image: myapp_server
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - redis
      - mongodb
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=redisPassword
      - DB_URL=postgres://postgres:rootpassword@postgresql:5432/postgres?sslmode=disable
      - MONGO_URL=mongodb://mongodb:27017
    volumes:
      - ./myapp/logs:/myapp/logs

  test:
    build:
      context: ./myapp
      dockerfile: Dockerfile.test
    image: test_image
    depends_on:
      - main_server
      - postgresql
      - redis
      - mongodb
      - db_init
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=redisPassword
      - DB_URL=postgres://postgres:rootpassword@postgresql:5432/postgres?sslmode=disable
      - MONGO_URL=mongodb://mongodb:27017

volumes:
  postgresql_data:
  mongodb_data:
