# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Test with docker-compose
      run: |
        docker-compose up --exit-code-from test
        docker-compose logs test > test.log
        docker-compose down
      continue-on-error: true

    - name: Upload test log
      uses: actions/upload-artifact@v2
      with:
        name: test-log
        path: test.log